### ISSUE TITLE
How to pass contract constructor parameters on deployment?

### ISSUE THREAD

**Issue by Latrasis** [eris-ltd/eris-contracts.js#28]
How do you pass in constructor parameters for a contract when deploying and what is the format?

**Comment by TinoSM** [comment]
Did you find anything?

I'm trying with:

- name: deployStorageK
  job:
    deploy:
      contract: csa.sol
      data: 9CA23F49A648810FF5293B16792D5C3AC3ABC1F8 "creatorEmail@sample.com"
      wait: true

And its basically breaking my contract (it creates sucesfully, but calls return errors)

**Comment by marc4gov** [comment]
I did it with:

```
jobs:
- name: deployMultisig
  job:
    deploy:
      contract: MultiSig.sol
      instance: all
      data: MultiSig 5 6 3 10000
      wait: true
```
with this Constructor:

```
function MultiSig(uint required, uint member_count, uint special_required, uint expiration) {
                _required = required;
                _member_count = member_count;
                _members_remaining = member_count;
                _special_required = special_required;
                _expiration = expiration;
                //
                _author = msg.sender;
        }
```
when calling the getInfo() :
```
function getInfo()
        constant
        returns(uint required, uint members, uint expiration, uint last_proposed_action) {
                        return (_required, _member_count, _expiration, _last_action_id);
                }
```

I got in the Javascript result code:

```
multisig info: [ { [String: '5581486560434678119'] s: 1, e: 18, c: [ 55814, 86560434678119 ] },
  { [String: '5'] s: 1, e: 0, c: [ 5 ] },
  { [String: '3'] s: 1, e: 0, c: [ 3 ] },
  { [String: '0'] s: 1, e: 0, c: [ 0 ] } ]
```
I can place 5=required, 0=last_proposed_action, rest is unclear to me

**Comment by marc4gov** [comment]
Sorry, this works:

```
jobs:

- name: deployMultisig
  job:
    deploy:
      contract: MultiSig.sol
      instance: all
      data: 5 6 3 100000
      wait: true
```

gives:

```
multisig getMemberCountInfo:  "6"
multisig required:  "5"
multisig info:  ["5","6","100000","0"]
multisig getExperationInfo:  "100000"
```
